name: CI/CD to GHCR

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t velprak/angular:latest .
          docker tag velprak/angular:latest velprak/angular:${{ github.sha }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: velpra
          password: ${{ secrets.DOCKER_PASSOWRD }}
      - name: Push to GHCR
        run: |
          docker push velprak/angular:latest
          docker push velprak/angular:${{ github.sha }}
